package:
  name: ommprotocol
  version: "0.1.1"

about:
  home: https://github.com/insilichem/ommprotocol
  license: LGPL
  summary: Easy to deploy MD protocols for OpenMM

source:
  path: ../

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - openmm
    - ruamel_yaml
    - parmed
    - openmoltools
    - mdtraj

test:
  imports:
    - ommprotocol
